"""Add new websites only mode

Revision ID: 2b156b897b48
Revises: 2a60a4affa2b
Create Date: 2026-06-14 00:05:24.210286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b156b897b48'
down_revision: Union[str, Sequence[str], None] = '2a60a4affa2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery_jobs', sa.Column('new_websites_only', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('discovery_jobs', sa.Column('known_domains_skipped', sa.Integer(), server_default='0', nullable=False))
    op.add_column('discovery_jobs', sa.Column('duplicate_candidates_skipped', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('discovery_jobs', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('discovery_jobs', 'websites_uncertain',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('discovery_jobs', 'contacts_found',
               existing_type=sa.INTEGER(),
               server_default='0',
               existing_nullable=False)
    op.alter_column('traffic_metrics', 'metric_type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('website_verifications', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_nullable=False)
    op.alter_column('websites', 'is_multitenant',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.create_check_constraint('chk_dj_kds', 'discovery_jobs', 'known_domains_skipped >= 0')
    op.create_check_constraint('chk_dj_dcs', 'discovery_jobs', 'duplicate_candidates_skipped >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('websites', 'is_multitenant',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('website_verifications', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('traffic_metrics', 'metric_type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'estimated_monthly_pageviews'::character varying"),
               existing_nullable=False)
    op.alter_column('discovery_jobs', 'contacts_found',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('discovery_jobs', 'websites_uncertain',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('discovery_jobs', 'attempt_number',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('chk_dj_dcs', 'discovery_jobs', type_='check')
    op.drop_constraint('chk_dj_kds', 'discovery_jobs', type_='check')
    op.drop_column('discovery_jobs', 'duplicate_candidates_skipped')
    op.drop_column('discovery_jobs', 'known_domains_skipped')
    op.drop_column('discovery_jobs', 'new_websites_only')
    # ### end Alembic commands ###
