"""create_core_discovery_schema

Revision ID: 2c8945ca246b
Revises: 
Create Date: 2026-06-12 17:55:17.074516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8945ca246b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_jobs',
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'completed_with_errors', 'failed', 'cancelled', name='discoveryjobstatus', native_enum=True), nullable=False),
    sa.Column('target_market', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('minimum_pageviews', sa.BigInteger(), nullable=False),
    sa.Column('maximum_queries', sa.Integer(), nullable=False),
    sa.Column('results_per_query', sa.Integer(), nullable=False),
    sa.Column('search_provider', sa.String(), nullable=False),
    sa.Column('traffic_provider', sa.String(), nullable=False),
    sa.Column('queries_generated', sa.Integer(), nullable=False),
    sa.Column('queries_completed', sa.Integer(), nullable=False),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.Column('duplicates_removed', sa.Integer(), nullable=False),
    sa.Column('candidates_filtered', sa.Integer(), nullable=False),
    sa.Column('sites_fetched', sa.Integer(), nullable=False),
    sa.Column('sites_verified', sa.Integer(), nullable=False),
    sa.Column('sites_rejected', sa.Integer(), nullable=False),
    sa.Column('sites_qualified', sa.Integer(), nullable=False),
    sa.Column('sites_upcoming', sa.Integer(), nullable=False),
    sa.Column('sites_traffic_missing', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('candidates_filtered >= 0', name='chk_dj_cf_filt'),
    sa.CheckConstraint('candidates_found >= 0', name='chk_dj_cf'),
    sa.CheckConstraint('duplicates_removed >= 0', name='chk_dj_dr'),
    sa.CheckConstraint('errors_count >= 0', name='chk_dj_ec'),
    sa.CheckConstraint('maximum_queries > 0', name='chk_dj_max_queries'),
    sa.CheckConstraint('minimum_pageviews >= 0', name='chk_dj_min_pv'),
    sa.CheckConstraint('queries_completed >= 0', name='chk_dj_qc'),
    sa.CheckConstraint('queries_generated >= 0', name='chk_dj_qg'),
    sa.CheckConstraint('results_per_query > 0', name='chk_dj_res_per_query'),
    sa.CheckConstraint('sites_fetched >= 0', name='chk_dj_sf'),
    sa.CheckConstraint('sites_qualified >= 0', name='chk_dj_sq'),
    sa.CheckConstraint('sites_rejected >= 0', name='chk_dj_sr'),
    sa.CheckConstraint('sites_traffic_missing >= 0', name='chk_dj_stm'),
    sa.CheckConstraint('sites_upcoming >= 0', name='chk_dj_su'),
    sa.CheckConstraint('sites_verified >= 0', name='chk_dj_sv'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('websites',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('homepage_url', sa.Text(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('current_verification_status', sa.Enum('verified', 'rejected', 'uncertain', 'fetch_failed', name='verificationstatus', native_enum=True), nullable=False),
    sa.Column('current_qualification_status', sa.Enum('qualified', 'upcoming', 'traffic_missing', 'rejected', 'needs_review', name='qualificationstatus', native_enum=True), nullable=False),
    sa.Column('manual_review_status', sa.Enum('pending', 'approved', 'rejected', 'needs_review', name='manualreviewstatus', native_enum=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(domain) > 0', name='chk_web_domain'),
    sa.CheckConstraint('length(homepage_url) > 0', name='chk_web_homepage'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_country'), 'websites', ['country'], unique=False)
    op.create_index(op.f('ix_websites_current_qualification_status'), 'websites', ['current_qualification_status'], unique=False)
    op.create_index(op.f('ix_websites_current_verification_status'), 'websites', ['current_verification_status'], unique=False)
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=True)
    op.create_index(op.f('ix_websites_language'), 'websites', ['language'], unique=False)
    op.create_index(op.f('ix_websites_last_checked_at'), 'websites', ['last_checked_at'], unique=False)
    op.create_index(op.f('ix_websites_manual_review_status'), 'websites', ['manual_review_status'], unique=False)
    op.create_table('contacts',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('discovery_job_id', sa.Uuid(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('contact_type', sa.Enum('advertising', 'partnerships', 'business', 'sales', 'editorial', 'editor', 'press', 'general', 'support', 'privacy', 'unknown', name='contacttype', native_enum=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('contact_form_url', sa.Text(), nullable=True),
    sa.Column('social_platform', sa.String(), nullable=True),
    sa.Column('social_url', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='chk_cnt_conf'),
    sa.CheckConstraint('email IS NOT NULL OR contact_form_url IS NOT NULL OR social_url IS NOT NULL', name='chk_cnt_method_exists'),
    sa.CheckConstraint('length(source_url) > 0', name='chk_cnt_src_url'),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_contact_type'), 'contacts', ['contact_type'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_is_active'), 'contacts', ['is_active'], unique=False)
    op.create_index(op.f('ix_contacts_is_primary'), 'contacts', ['is_primary'], unique=False)
    op.create_index(op.f('ix_contacts_website_id'), 'contacts', ['website_id'], unique=False)
    op.create_index('uix_contact_email_source', 'contacts', ['website_id', 'email', 'source_url'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_table('search_queries',
    sa.Column('discovery_job_id', sa.Uuid(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('requested_limit', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempt_count >= 0', name='chk_sq_ac'),
    sa.CheckConstraint('requested_limit > 0', name='chk_sq_rl'),
    sa.CheckConstraint('result_count >= 0', name='chk_sq_rc'),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discovery_job_id', 'query_text', name='uq_sq_job_query')
    )
    op.create_index('ix_sq_job_id', 'search_queries', ['discovery_job_id'], unique=False)
    op.create_index('ix_sq_status', 'search_queries', ['status'], unique=False)
    op.create_table('traffic_metrics',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('discovery_job_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('monthly_visits', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('pages_per_visit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('estimated_pageviews', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('growth_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('measurement_month', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='chk_tm_conf'),
    sa.CheckConstraint('estimated_pageviews >= 0', name='chk_tm_epv'),
    sa.CheckConstraint('length(provider) > 0', name='chk_tm_provider'),
    sa.CheckConstraint('monthly_visits >= 0', name='chk_tm_mv'),
    sa.CheckConstraint('pages_per_visit >= 0', name='chk_tm_ppv'),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_metrics_discovery_job_id'), 'traffic_metrics', ['discovery_job_id'], unique=False)
    op.create_index(op.f('ix_traffic_metrics_measurement_month'), 'traffic_metrics', ['measurement_month'], unique=False)
    op.create_index(op.f('ix_traffic_metrics_provider'), 'traffic_metrics', ['provider'], unique=False)
    op.create_index(op.f('ix_traffic_metrics_retrieved_at'), 'traffic_metrics', ['retrieved_at'], unique=False)
    op.create_index(op.f('ix_traffic_metrics_website_id'), 'traffic_metrics', ['website_id'], unique=False)
    op.create_table('website_verifications',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('discovery_job_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('verified', 'rejected', 'uncertain', 'fetch_failed', name='verificationstatus', native_enum=True), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('positive_reasons', sa.JSON(), nullable=False),
    sa.Column('negative_reasons', sa.JSON(), nullable=False),
    sa.Column('detected_categories', sa.JSON(), nullable=True),
    sa.Column('activity_status', sa.String(), nullable=True),
    sa.Column('classifier_version', sa.String(), nullable=False),
    sa.Column('homepage_title', sa.Text(), nullable=True),
    sa.Column('homepage_description', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='chk_wv_conf'),
    sa.CheckConstraint('length(classifier_version) > 0', name='chk_wv_ver'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='chk_wv_score'),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_verifications_discovery_job_id'), 'website_verifications', ['discovery_job_id'], unique=False)
    op.create_index(op.f('ix_website_verifications_score'), 'website_verifications', ['score'], unique=False)
    op.create_index(op.f('ix_website_verifications_status'), 'website_verifications', ['status'], unique=False)
    op.create_index(op.f('ix_website_verifications_verified_at'), 'website_verifications', ['verified_at'], unique=False)
    op.create_index(op.f('ix_website_verifications_website_id'), 'website_verifications', ['website_id'], unique=False)
    op.create_table('discovery_sources',
    sa.Column('website_id', sa.Uuid(), nullable=False),
    sa.Column('discovery_job_id', sa.Uuid(), nullable=False),
    sa.Column('search_query_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('result_url', sa.Text(), nullable=False),
    sa.Column('result_title', sa.Text(), nullable=True),
    sa.Column('result_snippet', sa.Text(), nullable=True),
    sa.Column('result_position', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('result_position > 0', name='chk_ds_pos'),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_id', 'discovery_job_id', 'query_text', 'result_url', name='uq_ds_website_job_query_url')
    )
    op.create_index(op.f('ix_discovery_sources_discovery_job_id'), 'discovery_sources', ['discovery_job_id'], unique=False)
    op.create_index(op.f('ix_discovery_sources_provider'), 'discovery_sources', ['provider'], unique=False)
    op.create_index(op.f('ix_discovery_sources_search_query_id'), 'discovery_sources', ['search_query_id'], unique=False)
    op.create_index(op.f('ix_discovery_sources_website_id'), 'discovery_sources', ['website_id'], unique=False)
    op.create_table('processing_errors',
    sa.Column('discovery_job_id', sa.Uuid(), nullable=True),
    sa.Column('website_id', sa.Uuid(), nullable=True),
    sa.Column('search_query_id', sa.Uuid(), nullable=True),
    sa.Column('stage', sa.Enum('query_generation', 'search', 'normalization', 'deduplication', 'filtering', 'fetching', 'verification', 'traffic', 'contact_discovery', 'contact_extraction', 'persistence', 'unknown', name='processingstage', native_enum=True), nullable=False),
    sa.Column('error_type', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('is_retryable', sa.Boolean(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('attempt_number > 0', name='chk_pe_attempt'),
    sa.CheckConstraint('length(error_type) > 0', name='chk_pe_type'),
    sa.CheckConstraint('length(message) > 0', name='chk_pe_msg'),
    sa.ForeignKeyConstraint(['discovery_job_id'], ['discovery_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_errors_created_at'), 'processing_errors', ['created_at'], unique=False)
    op.create_index(op.f('ix_processing_errors_discovery_job_id'), 'processing_errors', ['discovery_job_id'], unique=False)
    op.create_index(op.f('ix_processing_errors_is_retryable'), 'processing_errors', ['is_retryable'], unique=False)
    op.create_index(op.f('ix_processing_errors_search_query_id'), 'processing_errors', ['search_query_id'], unique=False)
    op.create_index(op.f('ix_processing_errors_stage'), 'processing_errors', ['stage'], unique=False)
    op.create_index(op.f('ix_processing_errors_website_id'), 'processing_errors', ['website_id'], unique=False)

    op.execute("DROP TYPE IF EXISTS discoveryjobstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS verificationstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS qualificationstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS manualreviewstatus CASCADE")
    op.execute("DROP TYPE IF EXISTS contacttype CASCADE")
    op.execute("DROP TYPE IF EXISTS processingstage CASCADE")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_errors_website_id'), table_name='processing_errors')
    op.drop_index(op.f('ix_processing_errors_stage'), table_name='processing_errors')
    op.drop_index(op.f('ix_processing_errors_search_query_id'), table_name='processing_errors')
    op.drop_index(op.f('ix_processing_errors_is_retryable'), table_name='processing_errors')
    op.drop_index(op.f('ix_processing_errors_discovery_job_id'), table_name='processing_errors')
    op.drop_index(op.f('ix_processing_errors_created_at'), table_name='processing_errors')
    op.drop_table('processing_errors')
    op.drop_index(op.f('ix_discovery_sources_website_id'), table_name='discovery_sources')
    op.drop_index(op.f('ix_discovery_sources_search_query_id'), table_name='discovery_sources')
    op.drop_index(op.f('ix_discovery_sources_provider'), table_name='discovery_sources')
    op.drop_index(op.f('ix_discovery_sources_discovery_job_id'), table_name='discovery_sources')
    op.drop_table('discovery_sources')
    op.drop_index(op.f('ix_website_verifications_website_id'), table_name='website_verifications')
    op.drop_index(op.f('ix_website_verifications_verified_at'), table_name='website_verifications')
    op.drop_index(op.f('ix_website_verifications_status'), table_name='website_verifications')
    op.drop_index(op.f('ix_website_verifications_score'), table_name='website_verifications')
    op.drop_index(op.f('ix_website_verifications_discovery_job_id'), table_name='website_verifications')
    op.drop_table('website_verifications')
    op.drop_index(op.f('ix_traffic_metrics_website_id'), table_name='traffic_metrics')
    op.drop_index(op.f('ix_traffic_metrics_retrieved_at'), table_name='traffic_metrics')
    op.drop_index(op.f('ix_traffic_metrics_provider'), table_name='traffic_metrics')
    op.drop_index(op.f('ix_traffic_metrics_measurement_month'), table_name='traffic_metrics')
    op.drop_index(op.f('ix_traffic_metrics_discovery_job_id'), table_name='traffic_metrics')
    op.drop_table('traffic_metrics')
    op.drop_index('ix_sq_status', table_name='search_queries')
    op.drop_index('ix_sq_job_id', table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index('uix_contact_email_source', table_name='contacts', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index(op.f('ix_contacts_website_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_primary'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_is_active'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_type'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_websites_manual_review_status'), table_name='websites')
    op.drop_index(op.f('ix_websites_last_checked_at'), table_name='websites')
    op.drop_index(op.f('ix_websites_language'), table_name='websites')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_index(op.f('ix_websites_current_verification_status'), table_name='websites')
    op.drop_index(op.f('ix_websites_current_qualification_status'), table_name='websites')
    op.drop_index(op.f('ix_websites_country'), table_name='websites')
    op.drop_table('websites')
    op.drop_table('discovery_jobs')

    op.execute("DROP TYPE IF EXISTS discoveryjobstatus")
    op.execute("DROP TYPE IF EXISTS verificationstatus")
    op.execute("DROP TYPE IF EXISTS qualificationstatus")
    op.execute("DROP TYPE IF EXISTS manualreviewstatus")
    op.execute("DROP TYPE IF EXISTS contacttype")
    op.execute("DROP TYPE IF EXISTS processingstage")

    # ### end Alembic commands ###
